In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("deliveries.csv")

In [7]:
print(df)

        match_id  inning                 batting_team  \
0              1       1          Sunrisers Hyderabad
1              1       1          Sunrisers Hyderabad
2              1       1          Sunrisers Hyderabad
3              1       1          Sunrisers Hyderabad
4              1       1          Sunrisers Hyderabad
5              1       1          Sunrisers Hyderabad
6              1       1          Sunrisers Hyderabad
7              1       1          Sunrisers Hyderabad
8              1       1          Sunrisers Hyderabad
9              1       1          Sunrisers Hyderabad
10             1       1          Sunrisers Hyderabad
11             1       1          Sunrisers Hyderabad
12             1       1          Sunrisers Hyderabad
13             1       1          Sunrisers Hyderabad
14             1       1          Sunrisers Hyderabad
15             1       1          Sunrisers Hyderabad
16             1       1          Sunrisers Hyderabad
17             1       1          Sunrisers Hyderabad
18             1       1          Sunrisers Hyderabad
19             1       1          Sunrisers Hyderabad
20             1       1          Sunrisers Hyderabad
21             1       1          Sunrisers Hyderabad
22             1       1          Sunrisers Hyderabad
23             1       1          Sunrisers Hyderabad
24             1       1          Sunrisers Hyderabad
25             1       1          Sunrisers Hyderabad
26             1       1          Sunrisers Hyderabad
27             1       1          Sunrisers Hyderabad
28             1       1          Sunrisers Hyderabad
29             1       1          Sunrisers Hyderabad
...          ...     ...                          ...
150430       636       2  Royal Challengers Bangalore
150431       636       2  Royal Challengers Bangalore
150432       636       2  Royal Challengers Bangalore
150433       636       2  Royal Challengers Bangalore
150434       636       2  Royal Challengers Bangalore
150435       636       2  Royal Challengers Bangalore
150436       636       2  Royal Challengers Bangalore
150437       636       2  Royal Challengers Bangalore
150438       636       2  Royal Challengers Bangalore
150439       636       2  Royal Challengers Bangalore
150440       636       2  Royal Challengers Bangalore
150441       636       2  Royal Challengers Bangalore
150442       636       2  Royal Challengers Bangalore
150443       636       2  Royal Challengers Bangalore
150444       636       2  Royal Challengers Bangalore
150445       636       2  Royal Challengers Bangalore
150446       636       2  Royal Challengers Bangalore
150447       636       2  Royal Challengers Bangalore
150448       636       2  Royal Challengers Bangalore
150449       636       2  Royal Challengers Bangalore
150450       636       2  Royal Challengers Bangalore
150451       636       2  Royal Challengers Bangalore
150452       636       2  Royal Challengers Bangalore
150453       636       2  Royal Challengers Bangalore
150454       636       2  Royal Challengers Bangalore
150455       636       2  Royal Challengers Bangalore
150456       636       2  Royal Challengers Bangalore
150457       636       2  Royal Challengers Bangalore
150458       636       2  Royal Challengers Bangalore
150459       636       2  Royal Challengers Bangalore

                       bowling_team  over  ball        batsman    non_striker  \
0       Royal Challengers Bangalore     1     1      DA Warner       S Dhawan
1       Royal Challengers Bangalore     1     2      DA Warner       S Dhawan
2       Royal Challengers Bangalore     1     3      DA Warner       S Dhawan
3       Royal Challengers Bangalore     1     4      DA Warner       S Dhawan
4       Royal Challengers Bangalore     1     5      DA Warner       S Dhawan
5       Royal Challengers Bangalore     1     6       S Dhawan      DA Warner
6       Royal Challengers Bangalore     1     7       S Dhawan      DA Warner
7       Royal Challengers Bangalore     2     1       S Dhawan      DA Warner
8       Royal Challengers Bangalore     2     2      DA Warner       S Dhawan
9       Royal Challengers Bangalore     2     3      DA Warner       S Dhawan
10      Royal Challengers Bangalore     2     4      DA Warner       S Dhawan
11      Royal Challengers Bangalore     2     5      DA Warner       S Dhawan
12      Royal Challengers Bangalore     2     6   MC Henriques       S Dhawan
13      Royal Challengers Bangalore     2     7   MC Henriques       S Dhawan
14      Royal Challengers Bangalore     3     1       S Dhawan   MC Henriques
15      Royal Challengers Bangalore     3     2   MC Henriques       S Dhawan
16      Royal Challengers Bangalore     3     3   MC Henriques       S Dhawan
17      Royal Challengers Bangalore     3     4   MC Henriques       S Dhawan
18      Royal Challengers Bangalore     3     5       S Dhawan   MC Henriques
19      Royal Challengers Bangalore     3     6   MC Henriques       S Dhawan
20      Royal Challengers Bangalore     4     1   MC Henriques       S Dhawan
21      Royal Challengers Bangalore     4     2   MC Henriques       S Dhawan
22      Royal Challengers Bangalore     4     3       S Dhawan   MC Henriques
23      Royal Challengers Bangalore     4     4       S Dhawan   MC Henriques
24      Royal Challengers Bangalore     4     5   MC Henriques       S Dhawan
25      Royal Challengers Bangalore     4     6       S Dhawan   MC Henriques
26      Royal Challengers Bangalore     5     1       S Dhawan   MC Henriques
27      Royal Challengers Bangalore     5     2   MC Henriques       S Dhawan
28      Royal Challengers Bangalore     5     3       S Dhawan   MC Henriques
29      Royal Challengers Bangalore     5     4   MC Henriques       S Dhawan
...                             ...   ...   ...            ...            ...
150430          Sunrisers Hyderabad    16     1       KL Rahul      SR Watson
150431          Sunrisers Hyderabad    16     2      SR Watson       KL Rahul
150432          Sunrisers Hyderabad    16     3       KL Rahul      SR Watson
150433          Sunrisers Hyderabad    16     4    Sachin Baby      SR Watson
150434          Sunrisers Hyderabad    16     5    Sachin Baby      SR Watson
150435          Sunrisers Hyderabad    16     6      SR Watson    Sachin Baby
150436          Sunrisers Hyderabad    17     1      SR Watson    Sachin Baby
150437          Sunrisers Hyderabad    17     2      SR Watson    Sachin Baby
150438          Sunrisers Hyderabad    17     3      SR Watson    Sachin Baby
150439          Sunrisers Hyderabad    17     4    Sachin Baby      STR Binny
150440          Sunrisers Hyderabad    17     5      STR Binny    Sachin Baby
150441          Sunrisers Hyderabad    17     6      STR Binny    Sachin Baby
150442          Sunrisers Hyderabad    18     1      STR Binny    Sachin Baby
150443          Sunrisers Hyderabad    18     2      STR Binny    Sachin Baby
150444          Sunrisers Hyderabad    18     3    Sachin Baby      STR Binny
150445          Sunrisers Hyderabad    18     4      STR Binny    Sachin Baby
150446          Sunrisers Hyderabad    18     5      STR Binny    Sachin Baby
150447          Sunrisers Hyderabad    18     6    Sachin Baby      STR Binny
150448          Sunrisers Hyderabad    19     1      STR Binny    Sachin Baby
150449          Sunrisers Hyderabad    19     2      CJ Jordan    Sachin Baby
150450          Sunrisers Hyderabad    19     3      CJ Jordan    Sachin Baby
150451          Sunrisers Hyderabad    19     4      CJ Jordan    Sachin Baby
150452          Sunrisers Hyderabad    19     5    Sachin Baby      CJ Jordan
150453          Sunrisers Hyderabad    19     6    Sachin Baby      CJ Jordan
150454          Sunrisers Hyderabad    20     1      CJ Jordan    Sachin Baby
150455          Sunrisers Hyderabad    20     2    Sachin Baby      CJ Jordan
150456          Sunrisers Hyderabad    20     3    Sachin Baby      CJ Jordan
150457          Sunrisers Hyderabad    20     4  Iqbal Abdulla    Sachin Baby
150458          Sunrisers Hyderabad    20     5    Sachin Baby  Iqbal Abdulla
150459          Sunrisers Hyderabad    20     6  Iqbal Abdulla    Sachin Baby

                   bowler  is_super_over  ...  bye_runs  legbye_runs  \
0                TS Mills              0  ...         0            0
1                TS Mills              0  ...         0            0
2                TS Mills              0  ...         0            0
3                TS Mills              0  ...         0            0
4                TS Mills              0  ...         0            0
5                TS Mills              0  ...         0            0
6                TS Mills              0  ...         0            1
7             A Choudhary              0  ...         0            0
8             A Choudhary              0  ...         0            0
9             A Choudhary              0  ...         0            0
10            A Choudhary              0  ...         0            0
11            A Choudhary              0  ...         0            0
12            A Choudhary              0  ...         0            0
13            A Choudhary              0  ...         0            0
14               TS Mills              0  ...         0            0
15               TS Mills              0  ...         0            0
16               TS Mills              0  ...         0            0
17               TS Mills              0  ...         0            0
18               TS Mills              0  ...         0            0
19               TS Mills              0  ...         0            0
20              YS Chahal              0  ...         0            0
21              YS Chahal              0  ...         0            0
22              YS Chahal              0  ...         0            0
23              YS Chahal              0  ...         0            0
24              YS Chahal              0  ...         0            0
25              YS Chahal              0  ...         0            0
26              S Aravind              0  ...         0            0
27              S Aravind              0  ...         0            0
28              S Aravind              0  ...         0            0
29              S Aravind              0  ...         0            0
...                   ...            ...  ...       ...          ...
150430        BCJ Cutting              0  ...         0            0
150431        BCJ Cutting              0  ...         0            0
150432        BCJ Cutting              0  ...         0            0
150433        BCJ Cutting              0  ...         0            0
150434        BCJ Cutting              0  ...         0            0
150435        BCJ Cutting              0  ...         0            0
150436  Mustafizur Rahman              0  ...         0            0
150437  Mustafizur Rahman              0  ...         0            0
150438  Mustafizur Rahman              0  ...         0            0
150439  Mustafizur Rahman              0  ...         0            0
150440  Mustafizur Rahman              0  ...         0            0
150441  Mustafizur Rahman              0  ...         0            0
150442            B Kumar              0  ...         0            0
150443            B Kumar              0  ...         0            0
150444            B Kumar              0  ...         0            0
150445            B Kumar              0  ...         0            0
150446            B Kumar              0  ...         0            1
150447            B Kumar              0  ...         0            0
150448  Mustafizur Rahman              0  ...         0            0
150449  Mustafizur Rahman              0  ...         0            0
150450  Mustafizur Rahman              0  ...         0            0
150451  Mustafizur Rahman              0  ...         0            1
150452  Mustafizur Rahman              0  ...         0            0
150453  Mustafizur Rahman              0  ...         0            0
150454            B Kumar              0  ...         0            0
150455            B Kumar              0  ...         0            0
150456            B Kumar              0  ...         0            0
150457            B Kumar              0  ...         0            1
150458            B Kumar              0  ...         0            0
150459            B Kumar              0  ...         0            0

        noball_runs  penalty_runs  batsman_runs  extra_runs  total_runs  \
0                 0             0             0           0           0
1                 0             0             0           0           0
2                 0             0             4           0           4
3                 0             0             0           0           0
4                 0             0             0           2           2
5                 0             0             0           0           0
6                 0             0             0           1           1
7                 0             0             1           0           1
8                 0             0             4           0           4
9                 1             0             0           1           1
10                0             0             6           0           6
11                0             0             0           0           0
12                0             0             0           0           0
13                0             0             4           0           4
14                0             0             1           0           1
15                0             0             0           0           0
16                0             0             0           0           0
17                0             0             3           0           3
18                0             0             1           0           1
19                0             0             1           0           1
20                0             0             0           0           0
21                0             0             1           0           1
22                0             0             0           0           0
23                0             0             1           0           1
24                0             0             1           0           1
25                0             0             1           0           1
26                0             0             1           0           1
27                0             0             1           0           1
28                0             0             1           0           1
29                0             0             2           0           2
...             ...           ...           ...         ...         ...
150430            0             0             1           0           1
150431            0             0             1           0           1
150432            0             0             0           0           0
150433            0             0             0           0           0
150434            0             0             1           0           1
150435            0             0             1           0           1
150436            0             0             0           0           0
150437            0             0             2           0           2
150438            0             0             0           0           0
150439            0             0             1           0           1
150440            0             0             6           0           6
150441            0             0             1           0           1
150442            0             0             0           0           0
150443            0             0             1           0           1
150444            0             0             1           0           1
150445            0             0             0           0           0
150446            0             0             0           1           1
150447            0             0             4           0           4
150448            0             0             1           0           1
150449            0             0             2           0           2
150450            0             0             0           0           0
150451            0             0             0           1           1
150452            0             0             2           0           2
150453            0             0             6           0           6
150454            0             0             1           0           1
150455            0             0             2           0           2
150456            0             0             0           0           0
150457            0             0             0           1           1
150458            0             0             1           0           1
150459            0             0             4           0           4

        player_dismissed dismissal_kind        fielder
0                    NaN            NaN            NaN
1                    NaN            NaN            NaN
2                    NaN            NaN            NaN
3                    NaN            NaN            NaN
4                    NaN            NaN            NaN
5                    NaN            NaN            NaN
6                    NaN            NaN            NaN
7                    NaN            NaN            NaN
8                    NaN            NaN            NaN
9                    NaN            NaN            NaN
10                   NaN            NaN            NaN
11             DA Warner         caught  Mandeep Singh
12                   NaN            NaN            NaN
13                   NaN            NaN            NaN
14                   NaN            NaN            NaN
15                   NaN            NaN            NaN
16                   NaN            NaN            NaN
17                   NaN            NaN            NaN
18                   NaN            NaN            NaN
19                   NaN            NaN            NaN
20                   NaN            NaN            NaN
21                   NaN            NaN            NaN
22                   NaN            NaN            NaN
23                   NaN            NaN            NaN
24                   NaN            NaN            NaN
25                   NaN            NaN            NaN
26                   NaN            NaN            NaN
27                   NaN            NaN            NaN
28                   NaN            NaN            NaN
29                   NaN            NaN            NaN
...                  ...            ...            ...
150430               NaN            NaN            NaN
150431               NaN            NaN            NaN
150432          KL Rahul         bowled            NaN
150433               NaN            NaN            NaN
150434               NaN            NaN            NaN
150435               NaN            NaN            NaN
150436               NaN            NaN            NaN
150437               NaN            NaN            NaN
150438         SR Watson         caught   MC Henriques
150439               NaN            NaN            NaN
150440               NaN            NaN            NaN
150441               NaN            NaN            NaN
150442               NaN            NaN            NaN
150443               NaN            NaN            NaN
150444               NaN            NaN            NaN
150445               NaN            NaN            NaN
150446               NaN            NaN            NaN
150447               NaN            NaN            NaN
150448         STR Binny        run out       DJ Hooda
150449               NaN            NaN            NaN
150450               NaN            NaN            NaN
150451               NaN            NaN            NaN
150452               NaN            NaN            NaN